apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
helmCharts:
- name: devxp-app
  releaseName: devxp-app
  version: 0.1.30
  repo: https://devxp-tech.github.io/helm-charts
  valuesInline:
    name: ${{values.component_id}}
    image:
      repository: diegoluisi/${{values.component_id}}
      tag: latest
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80