apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
helmCharts:
- name: devxp-app
  releaseName: devxp-app
  version: 0.1.30
  repo: https://devxp-tech.github.io/helm-charts
  valuesInline:
    name: ${{values.component_id}}
    image:
      repository: diegoluisi/${{values.component_id}}
      tag: latest
    autoscaling:
      enabled: ${{values.autoscaling}}
      minReplicas: ${{values.minReplicas}}
      maxReplicas: ${{values.maxReplicas}}
      targetCPUUtilizationPercentage: ${{values.targetCPUUtilizationPercentage}}
    resources:
      requests:
        memory: ${{values.resources.requests.memory}}
        cpu: ${{values.resources.requests.cpu}}
      limits:
        memory: ${{values.resources.limits.memory}}
        cpu: ${{values.resources.limits.cpu}}